name: "Adam157, G'awn Git"
markdown: kramdown

permalink: /blog/:year/:month/:day/:title

remote_theme: pmarsceill/just-the-docs

prose:
  rooturl: ''
  siteurl: 'http://adam157.github.io'
  media: 'assets'
  metadata:
#    _posts:
#      - name: "layout"
#        field:
#          label: "layout"
#          element: "text"
#          value: "post"
      - name: "date"
        field:
          label: "date"
          element: "text"
          value: "CURRENT_DATETIME"
      - name: "author"
        field:
          label: "author"
          element: "text"
          value: "Adam157"
      - name: "categories"
        field:
          label: "categories"
          element: "text"
          placeholder: "Enter categories"
      - name: "excerpt"
        field:
          label: "excerpt"
          element: "text"
          placeholder: "Enter excerpt"
      - name: "meta"
        field:
          label: "meta"
          element: "text"
          placeholder: "Enter metadata"

